
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1';
import Replicate from "https://esm.sh/replicate@0.25.2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

async function generateWithOpenAI(prompt: string) {
  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'gpt-image-1',
      prompt: prompt,
      n: 1,
      size: '1024x1024',
      quality: 'high',
      output_format: 'png'
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.statusText}`);
  }

  const data = await response.json();
  return data.data[0].b64_json;
}

async function generateWithStability(prompt: string, aspectRatio = '1:1', outputFormat = 'png', model = 'core') {
  const formData = new FormData();
  formData.append('prompt', prompt);
  formData.append('aspect_ratio', aspectRatio);
  formData.append('output_format', outputFormat);
  
  // Use the correct endpoint based on model
  const endpoint = model === 'ultra' 
    ? 'https://api.stability.ai/v2beta/stable-image/generate/ultra'
    : 'https://api.stability.ai/v2beta/stable-image/generate/core';

  console.log(`Using Stability API endpoint: ${endpoint}`);
  console.log(`Parameters: prompt="${prompt}", aspect_ratio="${aspectRatio}", output_format="${outputFormat}"`);

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${Deno.env.get('STABILITY_API_KEY')}`,
      'Accept': 'image/*'
    },
    body: formData,
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Stability API error:', response.status, errorText);
    console.error('Response headers:', Object.fromEntries(response.headers.entries()));
    throw new Error(`Stability API error: ${response.status} ${response.statusText} - ${errorText}`);
  }

  // Response is binary image data
  const imageData = await response.arrayBuffer();
  console.log(`Received image data: ${imageData.byteLength} bytes`);
  
  // Convert to base64
  const base64Data = btoa(String.fromCharCode(...new Uint8Array(imageData)));
  
  return base64Data;
}

async function generateWithReplicate(prompt: string, aspectRatio = '1:1') {
  const replicate = new Replicate({
    auth: Deno.env.get('REPLICATE_API_KEY'),
  });

  console.log(`Using Replicate API with prompt: "${prompt}", aspect_ratio: "${aspectRatio}"`);

  const output = await replicate.run(
    "black-forest-labs/flux-schnell",
    {
      input: {
        prompt: prompt,
        go_fast: true,
        megapixels: "1",
        num_outputs: 1,
        aspect_ratio: aspectRatio,
        output_format: "webp",
        output_quality: 80,
        num_inference_steps: 4
      }
    }
  );

  console.log("Replicate generation response:", output);

  if (!output || !output[0]) {
    throw new Error('No image generated by Replicate');
  }

  // Download the image and convert to base64
  const imageUrl = output[0];
  const imageResponse = await fetch(imageUrl);
  
  if (!imageResponse.ok) {
    throw new Error(`Failed to download image from Replicate: ${imageResponse.statusText}`);
  }

  const imageData = await imageResponse.arrayBuffer();
  const base64Data = btoa(String.fromCharCode(...new Uint8Array(imageData)));
  
  return base64Data;
}

async function generateImageWithFallback(prompt: string, aspectRatio = '1:1', outputFormat = 'png', model = 'core', preferredProvider = 'replicate') {
  const providers = preferredProvider === 'replicate' 
    ? ['replicate', 'openai', 'stability']
    : preferredProvider === 'openai'
    ? ['openai', 'replicate', 'stability'] 
    : ['stability', 'replicate', 'openai'];

  let lastError = null;

  for (const provider of providers) {
    try {
      console.log(`Attempting image generation with ${provider}...`);
      
      let base64Data;
      switch (provider) {
        case 'replicate':
          if (!Deno.env.get('REPLICATE_API_KEY')) {
            throw new Error('REPLICATE_API_KEY not configured');
          }
          base64Data = await generateWithReplicate(prompt, aspectRatio);
          break;
        case 'openai':
          if (!Deno.env.get('OPENAI_API_KEY')) {
            throw new Error('OPENAI_API_KEY not configured');
          }
          base64Data = await generateWithOpenAI(prompt);
          break;
        case 'stability':
          if (!Deno.env.get('STABILITY_API_KEY')) {
            throw new Error('STABILITY_API_KEY not configured');
          }
          base64Data = await generateWithStability(prompt, aspectRatio, outputFormat, model);
          break;
        default:
          throw new Error(`Unknown provider: ${provider}`);
      }

      console.log(`✅ Successfully generated image with ${provider}`);
      return { base64Data, provider };

    } catch (error) {
      console.error(`❌ ${provider} failed:`, error.message);
      lastError = error;
      continue;
    }
  }

  throw new Error(`All providers failed. Last error: ${lastError?.message}`);
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? ''
    );

    const { data: { user } } = await supabase.auth.getUser(
      req.headers.get('Authorization')?.replace('Bearer ', '') ?? ''
    );

    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const { prompt, conversationId, messageId, provider = 'replicate', aspectRatio, outputFormat, model } = await req.json();

    if (!prompt || !conversationId) {
      return new Response(JSON.stringify({ error: 'Prompt and conversation ID are required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Create image generation record
    const { data: generation, error: generationError } = await supabase
      .from('image_generations')
      .insert({
        user_id: user.id,
        conversation_id: conversationId,
        message_id: messageId,
        prompt: prompt,
        status: 'pending'
      })
      .select()
      .single();

    if (generationError) {
      console.error('Error creating generation record:', generationError);
      return new Response(JSON.stringify({ error: 'Failed to create generation record' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    try {
      console.log(`Starting image generation with preferred provider: ${provider}`);
      
      // Use fallback system to try multiple providers
      const { base64Data, provider: usedProvider } = await generateImageWithFallback(
        prompt, 
        aspectRatio, 
        outputFormat, 
        model, 
        provider
      );

      // Convert base64 to blob
      const binaryData = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
      
      // Generate unique filename with proper extension
      const extension = usedProvider === 'replicate' ? 'webp' : 'png';
      const filename = `${user.id}/${generation.id}.${extension}`;
      
      // Upload to Supabase Storage
      const { data: uploadData, error: uploadError } = await supabase.storage
        .from('generated-images')
        .upload(filename, binaryData, {
          contentType: usedProvider === 'replicate' ? 'image/webp' : 'image/png',
          cacheControl: '3600',
          upsert: false
        });

      if (uploadError) {
        console.error('Upload error:', uploadError);
        throw new Error('Failed to upload image to storage');
      }

      // Update generation record with success
      const { error: updateError } = await supabase
        .from('image_generations')
        .update({
          status: 'completed',
          image_path: uploadData.path,
          completed_at: new Date().toISOString()
        })
        .eq('id', generation.id);

      if (updateError) {
        console.error('Error updating generation record:', updateError);
      }

      // Get signed URL for the image
      const { data: signedUrl } = await supabase.storage
        .from('generated-images')
        .createSignedUrl(uploadData.path, 3600);

      return new Response(JSON.stringify({
        success: true,
        imageUrl: signedUrl?.signedUrl,
        generationId: generation.id,
        prompt: prompt,
        provider: usedProvider,
        downloadUrl: signedUrl?.signedUrl
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });

    } catch (error) {
      console.error('Error generating image:', error);
      
      // Update generation record with error
      await supabase
        .from('image_generations')
        .update({
          status: 'failed',
          error_message: error.message,
          completed_at: new Date().toISOString()
        })
        .eq('id', generation.id);

      return new Response(JSON.stringify({ 
        error: 'Failed to generate image', 
        details: error.message 
      }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

  } catch (error) {
    console.error('Function error:', error);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
